// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const putBlocks = `-- name: PutBlocks :batchexec
INSERT INTO blocks (subject, db_id, idx, part, data)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (subject, db_id, idx, part) DO UPDATE SET data = EXCLUDED.data
`

type PutBlocksBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type PutBlocksParams struct {
	Subject string
	DbID    string
	Idx     int64
	Part    int16
	Data    []byte
}

// PutBlocks inserts or updates the parts of the blocks of one commit. pgx sends all rows in one pipelined batch.
// An update of a part stays on the same page (HOT update), so the table does not grow. See
// migrations/00003_block_parts.sql.
func (q *Queries) PutBlocks(ctx context.Context, arg []PutBlocksParams) *PutBlocksBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Subject,
			a.DbID,
			a.Idx,
			a.Part,
			a.Data,
		}
		batch.Queue(putBlocks, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &PutBlocksBatchResults{br, len(arg), false}
}

func (b *PutBlocksBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *PutBlocksBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
