// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	Subject string
	DbID    string
	Idx     int64
	Part    int16
	Data    []byte
}

type Change struct {
	Subject string
	DbID    string
	Version int64
	Blocks  []int64
}

type Database struct {
	Subject      string
	DbID         string
	PageSize     int32
	PageCount    int64
	Version      int64
	LastCommitID []byte
	LeaseEpoch   int64
	LeaseID      []byte
	LeaseHolder  []byte
	LeaseGranted pgtype.Timestamptz
	LeaseExpires pgtype.Timestamptz
	Deleted      bool
}
