// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyCommit = `-- name: ApplyCommit :one
UPDATE databases
SET page_count = $3,
    version = version + 1,
    last_commit_id = $4,
    lease_expires = $5
WHERE subject = $1 AND db_id = $2
RETURNING version
`

type ApplyCommitParams struct {
	Subject      string
	DbID         string
	PageCount    int64
	LastCommitID []byte
	LeaseExpires pgtype.Timestamptz
}

func (q *Queries) ApplyCommit(ctx context.Context, arg ApplyCommitParams) (int64, error) {
	row := q.db.QueryRow(ctx, applyCommit,
		arg.Subject,
		arg.DbID,
		arg.PageCount,
		arg.LastCommitID,
		arg.LeaseExpires,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const changedSince = `-- name: ChangedSince :many
SELECT version, blocks FROM changes
WHERE subject = $1 AND db_id = $2 AND version > $3
ORDER BY version
`

type ChangedSinceParams struct {
	Subject string
	DbID    string
	Version int64
}

type ChangedSinceRow struct {
	Version int64
	Blocks  []int64
}

func (q *Queries) ChangedSince(ctx context.Context, arg ChangedSinceParams) ([]ChangedSinceRow, error) {
	rows, err := q.db.Query(ctx, changedSince, arg.Subject, arg.DbID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangedSinceRow
	for rows.Next() {
		var i ChangedSinceRow
		if err := rows.Scan(&i.Version, &i.Blocks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (subject, db_id, page_size)
VALUES ($1, $2, $3)
ON CONFLICT (subject, db_id) DO NOTHING
RETURNING subject, db_id, page_size, page_count, version, last_commit_id, lease_epoch, lease_id, lease_holder, lease_granted, lease_expires
`

type CreateDatabaseParams struct {
	Subject  string
	DbID     string
	PageSize int32
}

// CreateDatabase inserts nothing if the row already exists. The caller then locks and reads the existing row.
func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase, arg.Subject, arg.DbID, arg.PageSize)
	var i Database
	err := row.Scan(
		&i.Subject,
		&i.DbID,
		&i.PageSize,
		&i.PageCount,
		&i.Version,
		&i.LastCommitID,
		&i.LeaseEpoch,
		&i.LeaseID,
		&i.LeaseHolder,
		&i.LeaseGranted,
		&i.LeaseExpires,
	)
	return i, err
}

const databaseExists = `-- name: DatabaseExists :one
SELECT EXISTS (SELECT 1 FROM databases WHERE subject = $1 AND db_id = $2)
`

type DatabaseExistsParams struct {
	Subject string
	DbID    string
}

func (q *Queries) DatabaseExists(ctx context.Context, arg DatabaseExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, databaseExists, arg.Subject, arg.DbID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteBlocksFrom = `-- name: DeleteBlocksFrom :exec
DELETE FROM blocks
WHERE subject = $1 AND db_id = $2 AND idx >= $3
`

type DeleteBlocksFromParams struct {
	Subject string
	DbID    string
	Idx     int64
}

func (q *Queries) DeleteBlocksFrom(ctx context.Context, arg DeleteBlocksFromParams) error {
	_, err := q.db.Exec(ctx, deleteBlocksFrom, arg.Subject, arg.DbID, arg.Idx)
	return err
}

const extendLease = `-- name: ExtendLease :execrows
UPDATE databases
SET lease_expires = $4
WHERE subject = $1 AND db_id = $2 AND lease_epoch = $3 AND lease_holder IS NOT NULL
`

type ExtendLeaseParams struct {
	Subject      string
	DbID         string
	LeaseEpoch   int64
	LeaseExpires pgtype.Timestamptz
}

// ExtendLease updates no row if the epoch is not current or the lease was released. The caller then returns
// ErrFenced, or ErrNotFound if the database does not exist.
func (q *Queries) ExtendLease(ctx context.Context, arg ExtendLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendLease,
		arg.Subject,
		arg.DbID,
		arg.LeaseEpoch,
		arg.LeaseExpires,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fetchBlocks = `-- name: FetchBlocks :many
SELECT idx, part, data FROM blocks
WHERE subject = $1 AND db_id = $2
  AND idx >= $3 AND idx < $4
ORDER BY idx, part
`

type FetchBlocksParams struct {
	Subject string
	DbID    string
	First   int64
	Beyond  int64
}

type FetchBlocksRow struct {
	Idx  int64
	Part int16
	Data []byte
}

// FetchBlocks returns the stored parts of the blocks in a range, ordered by block and part. A block that was never
// written has no rows. The caller returns zeros for it.
func (q *Queries) FetchBlocks(ctx context.Context, arg FetchBlocksParams) ([]FetchBlocksRow, error) {
	rows, err := q.db.Query(ctx, fetchBlocks,
		arg.Subject,
		arg.DbID,
		arg.First,
		arg.Beyond,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchBlocksRow
	for rows.Next() {
		var i FetchBlocksRow
		if err := rows.Scan(&i.Idx, &i.Part, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabase = `-- name: GetDatabase :one
SELECT subject, db_id, page_size, page_count, version, last_commit_id, lease_epoch, lease_id, lease_holder, lease_granted, lease_expires FROM databases
WHERE subject = $1 AND db_id = $2
`

type GetDatabaseParams struct {
	Subject string
	DbID    string
}

func (q *Queries) GetDatabase(ctx context.Context, arg GetDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, arg.Subject, arg.DbID)
	var i Database
	err := row.Scan(
		&i.Subject,
		&i.DbID,
		&i.PageSize,
		&i.PageCount,
		&i.Version,
		&i.LastCommitID,
		&i.LeaseEpoch,
		&i.LeaseID,
		&i.LeaseHolder,
		&i.LeaseGranted,
		&i.LeaseExpires,
	)
	return i, err
}

const grantLease = `-- name: GrantLease :one
UPDATE databases
SET lease_epoch = lease_epoch + 1,
    lease_id = $3,
    lease_holder = $4,
    lease_granted = $5,
    lease_expires = $6
WHERE subject = $1 AND db_id = $2
RETURNING lease_epoch
`

type GrantLeaseParams struct {
	Subject      string
	DbID         string
	LeaseID      []byte
	LeaseHolder  []byte
	LeaseGranted pgtype.Timestamptz
	LeaseExpires pgtype.Timestamptz
}

func (q *Queries) GrantLease(ctx context.Context, arg GrantLeaseParams) (int64, error) {
	row := q.db.QueryRow(ctx, grantLease,
		arg.Subject,
		arg.DbID,
		arg.LeaseID,
		arg.LeaseHolder,
		arg.LeaseGranted,
		arg.LeaseExpires,
	)
	var lease_epoch int64
	err := row.Scan(&lease_epoch)
	return lease_epoch, err
}

const lockDatabase = `-- name: LockDatabase :one

SELECT subject, db_id, page_size, page_count, version, last_commit_id, lease_epoch, lease_id, lease_holder, lease_granted, lease_expires FROM databases
WHERE subject = $1 AND db_id = $2
FOR UPDATE
`

type LockDatabaseParams struct {
	Subject string
	DbID    string
}

// All SQL queries of the PostgreSQL store. sqlc generates internal/store/postgres/db from this file.
// LockDatabase locks the row of a database. Granting a lease, fencing and applying a commit all hold this lock, so
// they are serialized per database.
func (q *Queries) LockDatabase(ctx context.Context, arg LockDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, lockDatabase, arg.Subject, arg.DbID)
	var i Database
	err := row.Scan(
		&i.Subject,
		&i.DbID,
		&i.PageSize,
		&i.PageCount,
		&i.Version,
		&i.LastCommitID,
		&i.LeaseEpoch,
		&i.LeaseID,
		&i.LeaseHolder,
		&i.LeaseGranted,
		&i.LeaseExpires,
	)
	return i, err
}

const oldestChange = `-- name: OldestChange :one
SELECT min(version)::bigint FROM changes
WHERE subject = $1 AND db_id = $2
`

type OldestChangeParams struct {
	Subject string
	DbID    string
}

// OldestChange returns the oldest version in the change log, or null if the log is empty.
func (q *Queries) OldestChange(ctx context.Context, arg OldestChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, oldestChange, arg.Subject, arg.DbID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneChanges = `-- name: PruneChanges :exec
DELETE FROM changes
WHERE subject = $1 AND db_id = $2 AND version <= $3
`

type PruneChangesParams struct {
	Subject string
	DbID    string
	Version int64
}

// PruneChanges deletes the change log entries up to and including the given version.
func (q *Queries) PruneChanges(ctx context.Context, arg PruneChangesParams) error {
	_, err := q.db.Exec(ctx, pruneChanges, arg.Subject, arg.DbID, arg.Version)
	return err
}

const recordChange = `-- name: RecordChange :exec
INSERT INTO changes (subject, db_id, version, blocks)
VALUES ($1, $2, $3, $4)
ON CONFLICT (subject, db_id, version) DO NOTHING
`

type RecordChangeParams struct {
	Subject string
	DbID    string
	Version int64
	Blocks  []int64
}

// RecordChange adds the changed blocks of a commit to the change log. On a conflict it does nothing, so a repeated
// commit cannot fail here: the entry for that version already exists with the same content.
func (q *Queries) RecordChange(ctx context.Context, arg RecordChangeParams) error {
	_, err := q.db.Exec(ctx, recordChange,
		arg.Subject,
		arg.DbID,
		arg.Version,
		arg.Blocks,
	)
	return err
}

const releaseLease = `-- name: ReleaseLease :execrows
UPDATE databases
SET lease_holder = NULL
WHERE subject = $1 AND db_id = $2 AND lease_epoch = $3 AND lease_holder IS NOT NULL
`

type ReleaseLeaseParams struct {
	Subject    string
	DbID       string
	LeaseEpoch int64
}

func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseLease, arg.Subject, arg.DbID, arg.LeaseEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
